#!/usr/bin/env tsx
/**
 * OpenAPI Codegen for Lily SDK
 * 
 * Generates TypeScript types from the backend OpenAPI spec.
 * Usage: npx tsx scripts/codegen.ts [spec-path]
 * 
 * If no spec path is provided, uses the vendored spec at openapi/lily-backend.yaml.
 * Generated output goes to src/generated/ and is committed to the repo.
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT = resolve(__dirname, '..');
const DEFAULT_SPEC = resolve(ROOT, 'openapi', 'lily-backend.yaml');
const OUTPUT_DIR = resolve(ROOT, 'src', 'generated');
const OUTPUT_FILE = resolve(OUTPUT_DIR, 'types.ts');

function main() {
  const specPath = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_SPEC;

  if (!existsSync(specPath)) {
    console.error(`Error: OpenAPI spec not found at ${specPath}`);
    console.error('Provide a spec path as argument or place it at openapi/lily-backend.yaml');
    process.exit(1);
  }

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  console.log(`Generating types from: ${specPath}`);
  console.log(`Output: ${OUTPUT_FILE}`);

  try {
    execSync(
      `npx openapi-typescript "${specPath}" -o "${OUTPUT_FILE}" --additional-properties false`,
      { cwd: ROOT, stdio: 'inherit' },
    );
  } catch (error) {
    console.error('openapi-typescript failed. Ensure it is installed: npm install -D openapi-typescript');
    process.exit(1);
  }

  // Add header comment to generated file
  const generated = readFileSync(OUTPUT_FILE, 'utf-8');
  const header = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * 
 * Generated by scripts/codegen.ts from OpenAPI spec.
 * To regenerate: npm run codegen
 * 
 * Hand-written overrides belong in src/models/ and src/types/contracts.ts.
 * This file provides the raw schema types; client contracts add method signatures.
 */

`;
  writeFileSync(OUTPUT_FILE, header + generated);

  console.log('Codegen complete.');
}

main();
